// Post-build step (runs after the client and SSR Vite builds as part of `npm run build`).
// Hostinger serves dist/ as static files from public_html (LiteSpeed, .htaccess honoured). Every public route
// is written as a real folder (dist/about/index.html → /about/) containing the fully rendered page — so content,
// images and the enquiry form work before (and without) JavaScript — plus that route's title, description,
// robots, canonical, social tags, JSON-LD and preload hints. Also writes redirect pages, 404.html,
// sitemap.xml + sitemap-index.xml, robots.txt and the Apache/LiteSpeed config (.htaccess files).
import { access, mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const DIST = fileURLToPath(new URL('../dist/', import.meta.url))
const SSR_ENTRY = fileURLToPath(new URL('../dist-ssr/entry-server.js', import.meta.url))
const SEO_BLOCK = /<!-- seo:start[\s\S]*?<!-- seo:end -->/
const FONT_MARK = '<!-- preload:fonts -->'
const APP_MARK = '<!--app-html-->'
// Latin subsets of the two fonts used above the fold (body text and the 600-weight display headings).
const CRITICAL_FONTS = [/^manrope-latin-wght-normal-.*\.woff2$/, /^cormorant-garamond-latin-600-normal-.*\.woff2$/]

const ssr = await import(pathToFileURL(SSR_ENTRY).href)
const { NOT_FOUND_META, REDIRECTS, ROUTES, SITE_UPDATED, SITE_URL, DIAL_CODES, headFor, headTags, heroPreload, jsonLdFor, pagePath, pageUrl, render, serializeJsonLd } = ssr

const escapeHtml = (value) => String(value).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
const routeFile = (path) => (path === '/' ? 'index.html' : `${path.slice(1)}/index.html`)

function renderHead(route) {
  const head = headFor(route)
  const tags = headTags(route)
    .filter(([, , value]) => value != null)
    .map(([attr, key, value]) => attr === 'rel'
      ? `<link rel="${key}" href="${escapeHtml(value)}" />`
      : `<meta ${attr}="${key}" content="${escapeHtml(value)}" />`)
  const lines = [`<title>${escapeHtml(head.title)}</title>`, ...tags]
  const hero = heroPreload(route)
  if (hero) lines.push(`<link rel="preload" as="image" type="${hero.type}" href="${hero.href}" imagesrcset="${escapeHtml(hero.srcset)}" imagesizes="${escapeHtml(hero.sizes)}" fetchpriority="high" />`)
  const ld = jsonLdFor(route)
  if (ld) lines.push(`<script type="application/ld+json" id="ld-json">${serializeJsonLd(ld)}</script>`)
  return lines.join('\n    ')
}

async function renderPage(template, route, url) {
  if (!SEO_BLOCK.test(template) || !template.includes(APP_MARK)) throw new Error('dist/index.html is missing the seo:start/seo:end or app-html markers')
  const html = render(url)
  if (!html.includes('id="main-content"')) throw new Error(`Pre-render of ${url} produced no <main id="main-content">`)
  return template.replace(SEO_BLOCK, () => renderHead(route)).replace(APP_MARK, () => html)
}

/** Instant meta refresh: a fallback for the server-side 301 in .htaccess. */
function renderRedirect(to) {
  const target = pagePath(to)
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Redirecting…</title>
    <meta name="robots" content="noindex, follow" />
    <link rel="canonical" href="${pageUrl(to)}" />
    <meta http-equiv="refresh" content="0; url=${target}" />
    <script>location.replace(${JSON.stringify(target)} + location.search + location.hash)</script>
  </head>
  <body><p><a href="${target}">Continue to ${escapeHtml(pageUrl(to))}</a></p></body>
</html>
`
}

const indexable = () => ROUTES.filter((r) => !r.noindex)

function renderSitemap() {
  const urls = indexable().map((r) => `  <url><loc>${pageUrl(r.path)}</loc><lastmod>${r.updated ?? SITE_UPDATED}</lastmod></url>`)
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.join('\n')}\n</urlset>\n`
}

const renderSitemapIndex = () => `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <sitemap><loc>${SITE_URL}/sitemap.xml</loc><lastmod>${SITE_UPDATED}</lastmod></sitemap>
</sitemapindex>
`

// Allow everything: noindex pages must stay crawlable so Google can see their noindex tag, and CSS/JS must
// stay crawlable so Google can render pages.
const renderRobots = () => `User-agent: *\nAllow: /\n\nSitemap: ${SITE_URL}/sitemap-index.xml\n`

function renderHtaccess() {
  const host = new URL(SITE_URL).host
  const redirects = Object.entries(REDIRECTS).map(([from, to]) => `RewriteRule ^${from.slice(1)}/?$ ${pageUrl(to)} [R=301,L]`)
  return `# Generated by scripts/prerender.mjs — do not edit dist/.htaccess by hand.
# Every page is a real folder, so the site still works if the host replaces this file; when kept it adds
# single-hop 301s, the branded 404 page (with a real 404 status), security headers and caching.
Options -MultiViews -Indexes
DirectoryIndex index.html
ErrorDocument 404 /404.html

<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /

# www -> https://${host}
RewriteCond %{HTTP_HOST} ^www\\.${host.replace(/\./g, '\\.')}$ [NC]
RewriteRule ^(.*)$ ${SITE_URL}/$1 [R=301,L]

# Force HTTPS (the X-Forwarded-Proto check prevents loops behind a TLS-terminating proxy/CDN)
RewriteCond %{HTTPS} off
RewriteCond %{HTTP:X-Forwarded-Proto} !https
RewriteRule ^(.*)$ ${SITE_URL}/$1 [R=301,L]

# .../index.html -> folder URL
RewriteCond %{THE_REQUEST} \\s/(.*/)?index\\.html[\\s?]
RewriteRule ^(.*/)?index\\.html$ ${SITE_URL}/$1 [R=301,L]

# Duplicate routes -> preferred URL
${redirects.join('\n')}

# Page folders without the trailing slash -> canonical URL, in one HTTPS hop
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^(.*[^/])$ ${SITE_URL}/$1/ [R=301,L]
</IfModule>

<IfModule mod_headers.c>
Header always set X-Content-Type-Options "nosniff"
Header always set Referrer-Policy "strict-origin-when-cross-origin"
Header always set X-Frame-Options "SAMEORIGIN"
Header always set Permissions-Policy "camera=(), microphone=(), geolocation=(), payment=()"
# Browsers ignore HSTS on plain-HTTP responses, so this only takes effect after the HTTPS redirect.
Header always set Strict-Transport-Security "max-age=31536000"
# Pages, sitemaps and the manifest are revalidated on every visit so a new deploy shows at once.
<FilesMatch "\\.(html|xml|txt|webmanifest)$">
Header set Cache-Control "no-cache"
</FilesMatch>
# Icons keep stable names: cache for a week.
<FilesMatch "^(favicon\\.(ico|svg)|favicon-.*\\.png|apple-touch-icon\\.png|web-app-manifest-.*\\.png)$">
Header set Cache-Control "public, max-age=604800"
</FilesMatch>
</IfModule>

<IfModule mod_mime.c>
AddType application/manifest+json .webmanifest
AddType image/avif .avif
AddType image/webp .webp
</IfModule>
`
}

// Vite's hashed bundles (JS, CSS, fonts) never change content under the same name: cache for a year.
const ASSETS_HTACCESS = `# Generated by scripts/prerender.mjs: file names contain a content hash.
<IfModule mod_headers.c>
Header set Cache-Control "public, max-age=31536000, immutable"
</IfModule>
`
// Generated images keep their names between builds when unchanged; a month is a safe balance.
const IMAGES_HTACCESS = `# Generated by scripts/prerender.mjs
<IfModule mod_headers.c>
Header set Cache-Control "public, max-age=2592000"
</IfModule>
`

async function write(file, content) {
  const target = join(DIST, file)
  await mkdir(dirname(target), { recursive: true })
  await writeFile(target, content)
}

async function fontPreloads() {
  const files = await readdir(join(DIST, 'assets'))
  return CRITICAL_FONTS.map((pattern) => {
    const file = files.find((f) => pattern.test(f))
    if (!file) throw new Error(`Critical font ${pattern} not found in dist/assets`)
    return `<link rel="preload" as="font" type="font/woff2" href="/assets/${file}" crossorigin />`
  }).join('\n    ')
}

const shell = await readFile(join(DIST, 'index.html'), 'utf8')
if (!shell.includes(FONT_MARK)) throw new Error('dist/index.html is missing the preload:fonts marker')
const template = shell.replace(FONT_MARK, await fontPreloads())
for (const route of ROUTES) await write(routeFile(route.path), await renderPage(template, route, pagePath(route.path)))
for (const [from, to] of Object.entries(REDIRECTS)) await write(routeFile(from), renderRedirect(to))
await write('404.html', await renderPage(template, NOT_FOUND_META, '/404-not-found/'))
await write('sitemap.xml', renderSitemap())
await write('sitemap-index.xml', renderSitemapIndex())
await write('robots.txt', renderRobots())
await write('.htaccess', renderHtaccess())
await write('assets/.htaccess', ASSETS_HTACCESS)
await write('images/.htaccess', IMAGES_HTACCESS)
// Dialling codes for the PHP handler's server-side phone validation (no-JS posts send only the country).
await write('api/lib/dial-codes.json', JSON.stringify(DIAL_CODES))
await rm(fileURLToPath(new URL('../dist-ssr/', import.meta.url)), { recursive: true, force: true })

// Fail the build (and therefore the deploy) if any expected output is missing.
const expected = [...ROUTES.map((r) => routeFile(r.path)), ...Object.keys(REDIRECTS).map(routeFile), '404.html', 'sitemap.xml', 'sitemap-index.xml', 'robots.txt', '.htaccess', 'api/contact.php', 'api/lib/dial-codes.json', 'favicon.ico', 'site.webmanifest']
await Promise.all(expected.map((file) => access(join(DIST, file))))
console.log(`prerender: ${ROUTES.length} pages (${indexable().length} indexable), ${Object.keys(REDIRECTS).length} redirects, 404.html, sitemaps, robots.txt, .htaccess`)
